# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: webapps # Make sure you're using the correct namespace
spec:
  replicas: 1 # Adjust this based on your needs
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:4.4
          name: mongodb
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "my_database"

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: webapps # Ensure this matches your deployment namespace
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb

---
# Node.js Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: webapps # Ensure this matches your deployment namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: nodejsapp
          image: reginbilnesar/nodejsapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service:27017/my_database?authSource=admin"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "my_database"

---
# Node.js Application Service
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-service
  namespace: webapps # Ensure this matches your deployment namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nodejsapp
