# rolebinding.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secret-reader-binding
  namespace: webapps
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: webapps
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
